= Typeclasses

== What are typeclasses


A declaration of a type defines how that type in particular is created.
A declaration of a typeclass defines how a setof types are consumed or used in computations.

Typeclasses are like interfaces.

? Typeclasses are a means of ad hoc polymorphism aka constrained polymorphism

Data classes implement Typeclasses  (synonym for implements is instantiates)

= Bool example

Why not use the Read Typeclass

= Eq
The function type does not implement `Eq

`Eq`, `Ord`, `Enum`, `Bounded`, `Read`, and `Show` we can derive without manually providing instance methods

= Num

= Type-defaulting type classes

= Ord

`Eq` is a superclass of `Ord`

[source,haskell]
----
class Eq a => Ord a where
----

= Enum
= Show
Printing and `side effect`

= Read
String can contain invalid input that we can not parse
There are better and more robust ways to achieve this in Haskell

= Instances are dispatched by type


= Exercises
== Multiple Choice
1 -> c
2 -> b
3 -> a
4 -> c
5 -> a
== Does it type check
1 -> No because Person is no instance of Show
2 -> No because is no instance of Eq
3 -> Blah and Woot
4 ->